/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as UtilitiesRouteImport } from './routes/utilities'
import { Route as TechniciansRouteImport } from './routes/technicians'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResilienceRouteImport } from './routes/resilience'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as GisRouteImport } from './routes/gis'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesRoute = UtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniciansRoute = TechniciansRouteImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResilienceRoute = ResilienceRouteImport.update({
  id: '/resilience',
  path: '/resilience',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const GisRoute = GisRouteImport.update({
  id: '/gis',
  path: '/gis',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/assets': typeof AssetsRoute
  '/compliance': typeof ComplianceRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/emergency': typeof EmergencyRoute
  '/gis': typeof GisRoute
  '/operations': typeof OperationsRoute
  '/reports': typeof ReportsRoute
  '/resilience': typeof ResilienceRoute
  '/settings': typeof SettingsRoute
  '/technicians': typeof TechniciansRoute
  '/utilities': typeof UtilitiesRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/assets': typeof AssetsRoute
  '/compliance': typeof ComplianceRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/emergency': typeof EmergencyRoute
  '/gis': typeof GisRoute
  '/operations': typeof OperationsRoute
  '/reports': typeof ReportsRoute
  '/resilience': typeof ResilienceRoute
  '/settings': typeof SettingsRoute
  '/technicians': typeof TechniciansRoute
  '/utilities': typeof UtilitiesRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/assets': typeof AssetsRoute
  '/compliance': typeof ComplianceRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/emergency': typeof EmergencyRoute
  '/gis': typeof GisRoute
  '/operations': typeof OperationsRoute
  '/reports': typeof ReportsRoute
  '/resilience': typeof ResilienceRoute
  '/settings': typeof SettingsRoute
  '/technicians': typeof TechniciansRoute
  '/utilities': typeof UtilitiesRoute
  '/weather': typeof WeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/assets'
    | '/compliance'
    | '/digital-twin'
    | '/emergency'
    | '/gis'
    | '/operations'
    | '/reports'
    | '/resilience'
    | '/settings'
    | '/technicians'
    | '/utilities'
    | '/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/assets'
    | '/compliance'
    | '/digital-twin'
    | '/emergency'
    | '/gis'
    | '/operations'
    | '/reports'
    | '/resilience'
    | '/settings'
    | '/technicians'
    | '/utilities'
    | '/weather'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/assets'
    | '/compliance'
    | '/digital-twin'
    | '/emergency'
    | '/gis'
    | '/operations'
    | '/reports'
    | '/resilience'
    | '/settings'
    | '/technicians'
    | '/utilities'
    | '/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AssetsRoute: typeof AssetsRoute
  ComplianceRoute: typeof ComplianceRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  EmergencyRoute: typeof EmergencyRoute
  GisRoute: typeof GisRoute
  OperationsRoute: typeof OperationsRoute
  ReportsRoute: typeof ReportsRoute
  ResilienceRoute: typeof ResilienceRoute
  SettingsRoute: typeof SettingsRoute
  TechniciansRoute: typeof TechniciansRoute
  UtilitiesRoute: typeof UtilitiesRoute
  WeatherRoute: typeof WeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities': {
      id: '/utilities'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof UtilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technicians': {
      id: '/technicians'
      path: '/technicians'
      fullPath: '/technicians'
      preLoaderRoute: typeof TechniciansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resilience': {
      id: '/resilience'
      path: '/resilience'
      fullPath: '/resilience'
      preLoaderRoute: typeof ResilienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis': {
      id: '/gis'
      path: '/gis'
      fullPath: '/gis'
      preLoaderRoute: typeof GisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AssetsRoute: AssetsRoute,
  ComplianceRoute: ComplianceRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  EmergencyRoute: EmergencyRoute,
  GisRoute: GisRoute,
  OperationsRoute: OperationsRoute,
  ReportsRoute: ReportsRoute,
  ResilienceRoute: ResilienceRoute,
  SettingsRoute: SettingsRoute,
  TechniciansRoute: TechniciansRoute,
  UtilitiesRoute: UtilitiesRoute,
  WeatherRoute: WeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
